server:
  port: 30080
spring:
  http:
    encoding:
      force: true
      charset: UTF-8
  mvc:
    favicon:
      enabled: false
  messages:
    basename: i18n/messages
logging:
#  file: log/sendfile.log
  level:
#    root: DEBUG
    cn.pers.qhl.sendfile.*: DEBUG
sendfile:
  share:
    ttl-options:  # 单位：M/H/D。永不过期：-1
      - value: 1H
      - value: 1D
        default-option: true
      - value: 7D
      - value: 30D
    scan-interval: 1H  # 单位：M/H/D
    max-file-size: 10GB # 单位：B/KB/MB/GB/TB。默认单位：B。任意大小：-1
  admin-password: 123