server:
  port: 30080
spring:
  http:
    encoding:
      force: true
      charset: UTF-8
logging:
#  file: log/sendfile.log
  level:
#    root: DEBUG
    cn.pers.qhl.sendfile.*: DEBUG
sendfile:
  share:
    ttl: 1  # 单位：天
    scan-interval: 1  # 单位：小时
    max-file-size: -1 # 单位：MB