server:
  port: 30080
spring:
  http:
    encoding:
      force: true
      charset: UTF-8
  mvc:
    favicon:
      enabled: false
logging:
#  file: log/sendfile.log
  level:
#    root: DEBUG
    cn.pers.qhl.sendfile.*: DEBUG
sendfile:
  share:
    ttl-options:
      - name: 1小时
        value: 1H
      - name: 1天
        value: 1D
        default-option: true
      - name: 7天
        value: 7D
      - name: 30天
        value: 30D
    scan-interval: 1  # 单位：小时
    max-file-size: 500 # 单位：MB