server:
  port: 30080
spring:
  http:
    encoding:
      force: true
      charset: UTF-8
logging:
#  file: log/sendfile.log
  level:
#    root: DEBUG
    cn.pers.qhl.sendfile.*: DEBUG
sendfile:
  share:
    ttl-options:
      - name: 1小时
        value: 1H
      - name: 6小时
        value: 6H
      - name: 1天
        value: 1D
        default-option: true
      - name: 1星期
        value: 1W
      - name: 永不过期
        value: -1
    scan-interval: 1  # 单位：小时
    max-file-size: -1 # 单位：MB