server:
  port: 8090
spring:
  http:
    encoding:
      force: true
      charset: UTF-8
  servlet:
    multipart:
      maxFileSize: -1     # 不限制上传文件大小
      maxRequestSize: -1  # 不限制上传文件大小
logging:
#  file: log/sendfile.log
  level:
#    root: DEBUG
    cn.pers.qhl.sendfile.*: DEBUG